name: "Release packages"

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: Write-Output $env:GITHUB_REF.replace("refs/tags/v","") | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: python -m pip install -r requirements.txt
      - name: "Install pyinstaller"
        run: pip install pyinstaller
      - name: "Create package"
        run: pyinstaller --onefile app.py --icon=StayAwake.ico --windowed --noconsole --name="StayAwake"
      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.RELEASE_VERSION }}_windows"
          release_name: "Release ${{ github.ref }} for Windows"
          draft: false
          prerelease: false
          files: |
            dist/*
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: python -m pip install -r requirements.txt
      - name: "Install pyinstaller"
        run: pip install pyinstaller
      - name: "Create package"
        run: pyinstaller --onefile app.py --icon=StayAwake.ico --windowed --noconsole --name="StayAwake"
      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.RELEASE_VERSION }}_linux"
          release_name: "Release ${{ github.ref }} for Linux"
          draft: false
          prerelease: false
          files: |
            dist/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: python -m pip install -r requirements.txt
      - name: "Install pyinstaller"
        run: pip install pyinstaller
      - name: "Create package"
        run: pyinstaller --onefile app.py --icon=StayAwake.ico --windowed --noconsole --name="StayAwake"
      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.RELEASE_VERSION }}_macos"
          release_name: "Release ${{ github.ref }} for MacOS"
          draft: false
          prerelease: false
          files: |
            dist/*
